server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://47.109.63.90:3306/yyq?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: yyQ@2023
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
#日志输出环境 对应为logback-spring.xml的springProfile的name 目前默认生产环境 输出info级别到控制台和日志文件
  profiles:
    active: prod

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yyq.wedding.domain
  configuration:
    autoRuntimeDialect: true

#全局配置文件，该文件不提交
wedding:
  #设置抽奖持续时间（单位：秒）
  luckDrawTimeOne: 10
  #设置抽奖一期间指定发送的弹幕内容
  luckDrawTextOne: 卢本伟牛逼




